version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/mattermost/mattermost-server/v5
    versions:
    - 5.31.0
    - 5.31.1
    - 5.32.0
    - 5.32.1
    - 5.33.0
    - 5.33.1
    - 5.33.2
    - 5.33.3
    - 5.34.1
