---

dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"

# Any typos we should ignore?
excluded_words:
  - typoci
  - circleci
  - CircleCI
  - Mattermost
  - mattermost
  - mattermost-server
  - thoas
  - TomTucka
  - antihax
  - stretchr
  - unmarshal
  - Unmarshal
  - dataToUnmarshal
  - unmarshaling
  - kvstore
  - mattermostexecutor
  - cibuilds
  - gcflags
  - tada

# Would you like filenames to also be spellchecked?
spellcheck_filenames: false
